#!/usr/bin/env bash
set -euo pipefail

# By default, we assume this script is ran in the thrift-build Docker container
THRIFT_SRC="${THRIFT_SRC:-/thrift/src}"
THRIFT_BUILD="${THRIFT_BUILD:-/thrift/build}" && mkdir -p "${THRIFT_BUILD}"

CMAKE_FLAGS=$(cat <<EOF
-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=11
-DTHRIFT_COMPILER_GO=ON -DTHRIFT_COMPILER_CL=OFF -DTHRIFT_COMPILER_CPP=OFF
-DTHRIFT_COMPILER_D=OFF -DTHRIFT_COMPILER_DART=OFF -DTHRIFT_COMPILER_DELPHI=OFF -DTHRIFT_COMPILER_ERL=OFF
-DTHRIFT_COMPILER_GV=OFF -DTHRIFT_COMPILER_HAXE=OFF -DTHRIFT_COMPILER_HTML=OFF -DTHRIFT_COMPILER_JAVA=OFF
-DTHRIFT_COMPILER_JS=OFF -DTHRIFT_COMPILER_LUA=OFF -DTHRIFT_COMPILER_LUA=OFF -DTHRIFT_COMPILER_MARKDOWN=OFF
-DTHRIFT_COMPILER_NETSTD=OFF -DTHRIFT_COMPILER_OCAML=OFF -DTHRIFT_COMPILER_PERL=OFF -DTHRIFT_COMPILER_PHP=OFF
-DTHRIFT_COMPILER_PY=OFF -DTHRIFT_COMPILER_RB=OFF -DTHRIFT_COMPILER_RS=OFF -DTHRIFT_COMPILER_ST=OFF
-DTHRIFT_COMPILER_SWIFT=OFF -DTHRIFT_COMPILER_XML=OFF -DTHRIFT_COMPILER_XSD=OFF
EOF
)

OS_FLAGS=""
if [ "$(uname -s)" == "Darwin" ]; then
    # Forcing the Configuration type forces a Release build on OSX
    OS_FLAGS="-DCMAKE_CONFIGURATION_TYPES=Release -G Xcode"
fi

pushd "${THRIFT_BUILD}"
cmake ${CMAKE_FLAGS} ${OS_FLAGS} "${THRIFT_SRC}"/compiler/cpp
cmake --build .
popd
